#!/usr/bin/env bash
(set -o igncr) 2>/dev/null && set -o igncr; # This comment is required.
### The above line ensures that the script can be run on Cygwin/Linux even with Windows CRNL.

######
### Generates lua file to create data from .png for https://mods.factorio.com/mod/decals
### Original source: https://github.com/ZwerOxotnik/factorio-decals
######


main() {

### Check if identify command exists
### https://sox.sourceforge.net/
local has_errors=false
if ! command -v identify &> /dev/null; then
	echo "identify: command not found"
	has_errors=true
fi
if [ $has_errors = true ] ; then
	exit 1
fi


local bold=$(tput bold)
local normal=$(tput sgr0)


### Find info.json
local SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR
local infojson_exists=false
local script_file=`basename "$0"`
if [[ -s "$SCRIPT_DIR/info.json" ]]; then
    local infojson_exists=true
else
	cd ..
	if [[ -s "$PWD/info.json" ]]; then
		local infojson_exists=true
	else
		cd $SCRIPT_DIR
	fi
fi
local mod_folder=$PWD

local DECAL_LIST_FILE=decal_list.lua
local DECAL_LIST_SCENARIO_FILE=read_and_rename_to-decal_list.lua


### Get mod name and version from info.json
if [ $infojson_exists = true ] ; then
	local MOD_NAME=$(jq -r '.name' info.json)
	if ! command -v jq &> /dev/null; then
		echo "Please install jq https://stedolan.github.io/jq/"
	fi
fi


echo "you're in ${bold}$mod_folder${normal}"


read -r -p "Complete path to folder of images: $MOD_NAME/" folder_name
local folder_path=$mod_folder/$folder_name
if [ ! -z "$folder_name" ]; then
	local rel_folder_path="${folder_name}/"
fi

local DECAL_LIST_PATH="$folder_path/$DECAL_LIST_FILE"
local DECAL_LIST_SCENARIO_PATH="$folder_path/$DECAL_LIST_SCENARIO_FILE"
rm -f $DECAL_LIST_PATH
rm -f $DECAL_LIST_SCENARIO_PATH

echo '
--[[###
This file auto-generated by script of https://github.com/ZwerOxotnik/factorio-decals
Add "decals >= 2.0.0" in your dependencies
This file should be in root folder of a mod!!!
]]--###

' >> $DECAL_LIST_PATH

echo '
--[[###
This file auto-generated by script of https://github.com/ZwerOxotnik/factorio-decals
WARNING: This file should be in scenario folder of a mod and should renames as "decal_list.lua"!!!
WARNING: path to images probably is not correct. Read https://lua-api.factorio.com/latest/Concepts.html#SpritePath
]]--###

' >> $DECAL_LIST_SCENARIO_PATH

echo "local data_stage_data = {" >> $DECAL_LIST_PATH
echo "return {" >> $DECAL_LIST_SCENARIO_PATH

local format=*.png
local files=($(find $folder_path/ -name "$format" -type f))
for path in "${files[@]}"; do
	local name="$(basename -- $path)"
	local name=${name%.*}
	echo -e "\t[\"$name\"] = {" >> $DECAL_LIST_PATH
	echo -e "\t\tfilename = \"__${MOD_NAME}__/$rel_folder_path$name.png\"", >> $DECAL_LIST_PATH
	echo -e "\t\t$(identify -format 'width=%w, height=%h,' $path)" >> $DECAL_LIST_PATH
	echo -e "\t}," >> $DECAL_LIST_PATH
	# TODO: fix path \/
	echo -e "\t[\"$name\"] = \"file/$(basename -- $rel_folder_path)/$name\"," >> $DECAL_LIST_SCENARIO_PATH
done
echo "}" >> $DECAL_LIST_PATH
echo "}" >> $DECAL_LIST_SCENARIO_PATH
echo "" >> $DECAL_LIST_PATH


echo '
for name, _data in pairs(data_stage_data) do
	_data.type = _data.type or "sprite"
	_data.name = _data.name or (name .. "_decal")
end


if decals_mod then
	return data_stage_data
else
	local control_stage_data = {}
	for name, _data in pairs(data_stage_data) do
		if _data.type == "sprite" then
			control_stage_data[name] = _data.name
		else
			control_stage_data[name] = _data.type .. "/" .. _data.name
		end
	end
	return control_stage_data
end' >> $DECAL_LIST_PATH


echo ""
echo "You're almost ready!${bold}"
echo "# Add string \"decals >= 2.0.0\" in dependencies of ${MOD_NAME}/info.json, example: '\"dependencies\": [\"decals >= 2.0.0\"]'"

echo "${normal}"
echo ""

echo "if you found a bug or you have a problem with script etc, please, let me know"
echo "This script created by ZwerOxotnik (source: https://github.com/ZwerOxotnik/factorio-decals)"
}
main
